[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy<2.0",
    "pandas>=2.3.2",
    "pandas-ta>=0.3.14b0",
    "plotly>=6.3.0",
    "streamlit>=1.49.1",
    "yfinance>=0.2.65",
]
